# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "windows-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm run build
    displayName: "npm run build"

  - script: |
      dir
    displayName: "list cwd contents (verify build)"

  - task: AzureFileCopy@4
    inputs:
      sourcePath: "$(Build.Repository.LocalPath)/build"
      azureSubscription: "<subscription-id>"
      destination: AzureBlob
      storage: <blob storage account name>
      containerName: "$web"
    displayName: "copy content to web container"
